### ISSUE TITLE
im trying to figure out what you have contributed?

### ISSUE THREAD

**Issue by pscanlon1** [phillipcurl/ng2-layout#1]
Am I missing all the work these 100 people have done?

**Comment by phillipcurl** [comment]
What? I'm literally the only contributor to this project, and I abandoned it after I stopped working with Angular as often as I was. The second line of the README clearly states: "THIS PROJECT IS STILL UNDER HEAVY DEVELOPMENT. DO NOT USE."

**Comment by pscanlon1** [comment]
Ok so I didnt miss any work then, right?
